version: "3.9"  # optional since v1.27.0
services:
  source_mysql:
    image: mysql
    container_name: source_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "23307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./mount/source_mysql:/docker-entrypoint-initdb.d"
    networks:
      - default

  target_mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./mount/target_mysql:/docker-entrypoint-initdb.d"
    networks:
      - default
    container_name: target_mysql

  spark-master:
    image: docker.io/bitnami/spark:3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '18080:8080'
    networks:
      - default

  spark-worker-1:
    image: docker.io/bitnami/spark:3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1500M
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '18081:8081'
    networks:
      - default

  zeppelin:
    image: cwsddbdw/zeppelin-1.10.0:py3.8
    container_name: zeppelin
    environment:
      - SPARK_HOME=/opt/spark
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - default
    ports:
      - '27077:7077'
      - '28080:8080'
    volumes:
      - ./mount/spark:/opt/spark
networks:
  default: